menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/lyloou
    GitHub: https://github.com/lyloou
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-80542932-1 

# Copyright Infomation
startyear: 2016
